### PR TITLE
`SELFDESTRUCT` warning

### LINKED ISSUE #271: Shanghai support
The Shanghai Execution Layer upgrade is around the corner. I have listed what I think that should be changed in `huff-rs`: 

- [x] Add support for `PUSH0` ([EIP-3855](https://eips.ethereum.org/EIPS/eip-3855)) (#272)
- [ ] Warn `SELFDESTRUCT` users as recommended in the upgrade spec ([EIP-6049](https://eips.ethereum.org/EIPS/eip-6049)) (#275)

Am I missing something ?

### Ressources

- [Shanghai Network Upgrade Specification](https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/shanghai.md)

### PR DESCRIPTION
**Pull request by MathisGD**
## Overview

Issue a warning when `selfdestruct` is used, as recommended in the [Shanghai spec](https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/shanghai.md). 
It interacts weirdly with the spinner but it works ^^

```sh
% huffc temp.huff
⠋ Compiling...Warning: "selfdestruct" has been deprecated. The underlying opcode will eventually undergo breaking changes, and its use is not recommended.
⠙ Compiling... 
```

Fixes #271. Inspired by https://github.com/ethereum/solidity/pull/13884. 

I ran all the checks.

### CODE REVIEW

**Review by cheethas — CHANGES_REQUESTED** [review]
Ah very nice! Could you rebase this onto stage, the lexer implementation has recently changed in  https://github.com/huff-language/huff-rs/pull/258

**Comment by MathisGD** [comment]
Done @cheethas :-)

**Comment by clabby** [comment]
Great idea to add a warning, only concern here is that this breaks `foundry-huff` for all contracts that use `SELFDESTRUCT`. Would be great to add a flag that suppresses warnings or add this as a tracing warning.

**Comment by MathisGD** [comment]
I fear that if it is not shown by default, people will not notice it. Is the issue with `foundry-huff` a big deal ? We could even throw an error each time (with potentially a flag that can deactivate this error), as `selfdestruct` is really not supposed to be used. Wdyt ?

**Comment by cheethas** [comment]
> I fear that if it is not shown by default, people will not notice it. Is the issue with `foundry-huff` a big deal ? We could even throw an error each time (with potentially a flag that can deactivate this error), as `selfdestruct` is really not supposed to be used. Wdyt ?

Good catch by vex I didnt think of this! I agree people won't see it if it is not default, however as vex said, a suppress warning flag would be required to not break foundry huff (which we can leave on by default in the foundry-huff package).

**Comment by MathisGD** [comment]
As [EIP-6780](https://eips.ethereum.org/EIPS/eip-6780) deactivating `SELFDESTRUCT` will be deprecated in Cancun ([source](https://tim.mirror.xyz/8hWUEmXWt-ZYNh4UlU4dMhsV9aNo26oNigCuy-z1k38)), I don't think that it's worth adding this to huffmate now in the end.

**Pull request closed without merging**
