### PR TITLE
style(huff_cli): print newline after bytecode

### PR DESCRIPTION
**Pull request by MathisGD**
## Overview

Print a newline after printing the bytecode (or runtime bytecode) in the CLI.

- [x] I ran all the recommanded checks

### CODE REVIEW

**Comment by clabby** [comment]
Hi Mathis! Thanks for the PR. We don't print a newline after the bytecode so that the output is consumable by FFI in foundry-huff.

See: [https://book.getfoundry.sh/cheatcodes/ffi](https://book.getfoundry.sh/cheatcodes/ffi)

**Comment by MathisGD** [comment]
Oh yes ! I thought there must be a reason, but I tried foundry-huff with it and it worked, strangely.

Closing this PR then.

**Comment by cheethas** [comment]
@MathisGD @clabby Could there be merit to introducing this behaviour as an extra command, say --bn (-b with newline ) or --rn (-r with newline)?

**Comment by MathisGD** [comment]
Idk if this is not introducing too much complexity for a very little improvement.. But if some people really need it, then I could re-open it with these modifications.

**Pull request closed without merging**
