### PR TITLE
feat: use dencun opcode for TLOAD and TSTORE

### PR DESCRIPTION
**Pull request by Mouradif**
## Overview

Since this commit: 33d2bd8e42de96fbdd31c4894c5a4eafe8c4bdbc TLOAD and TSTORE opcodes were available as B3 and B4 respectively. This commit updates these 2 to use the 5C and 5D used on Ethereum

### CODE REVIEW

**Comment by MathisGD** [comment]
why in a first place have they been put to B3 and B4? was the EIP changed in between?

**Comment by Mouradif** [comment]
That's a good question. I searched around and tried to find it. I There's another project that has the same thing (murph, the huff bytecode to huff decompiler) maybe it's for some other chain

**Comment by MathisGD** [comment]
I just found the reason why: the EIP has been updated. And someone already [fixed it](https://github.com/huff-language/huff-rs/pull/294) actually, but it has been merged on the stage branch. I'll see to merge it asap to get this fixed! Thanks for the notice!

**Comment by Mouradif** [comment]
Oh sweet! Okay, so I'll just close this PR then.

**Comment by Mouradif** [comment]
Oh sweet! Okay, so I'll just close this PR then.

**Pull request closed without merging**
